"""change fit_explanation to json

Revision ID: 0f4632632f8a
Revises: 4d3271fb2f5c
Create Date: 2025-12-15 13:36:12.113094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4632632f8a'
down_revision: Union[str, Sequence[str], None] = '4d3271fb2f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'candidates',
    'fit_explanation',
    existing_type=sa.TEXT(),
    type_=sa.JSON(),
    existing_nullable=True,
    postgresql_using="fit_explanation::json"
)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'fit_explanation',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
