"""added jd_url and job_recruiters relationship

Revision ID: 157a50b4842c
Revises: 1355724b75c4
Create Date: 2025-12-12 18:47:04.893533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157a50b4842c'
down_revision: Union[str, Sequence[str], None] = '1355724b75c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('jd_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'jd_url')
    # ### end Alembic commands ###
