"""add ImportedCandidate table

Revision ID: 1a4067788234
Revises: c9a49148e516
Create Date: 2025-12-06 12:27:37.044258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4067788234'
down_revision: Union[str, Sequence[str], None] = 'c9a49148e516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imported_candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('current_location', sa.String(), nullable=True),
    sa.Column('current_address', sa.String(), nullable=True),
    sa.Column('permanent_address', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('job_applied', sa.String(), nullable=True),
    sa.Column('application_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('referral', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('current_employer', sa.String(), nullable=True),
    sa.Column('previous_employers', sa.String(), nullable=True),
    sa.Column('notice_period', sa.String(), nullable=True),
    sa.Column('expected_salary', sa.String(), nullable=True),
    sa.Column('preferred_location', sa.String(), nullable=True),
    sa.Column('languages_known', sa.String(), nullable=True),
    sa.Column('social_profiles', sa.String(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imported_candidates')
    # ### end Alembic commands ###
