ALTER TABLE candidates ADD COLUMN IF NOT EXISTS parsed_json JSONB;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS parsed_at TIMESTAMP;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS parser_version VARCHAR(50);
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS raw_text TEXT;
