"""Add BGV fields

Revision ID: 21eced7f43e0
Revises: a8942d5260af
Create Date: 2025-12-29 14:43:55.461581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21eced7f43e0'
down_revision: Union[str, Sequence[str], None] = 'a8942d5260af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('bgv_status', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('bgv_vendor_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'vendors', ['bgv_vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'bgv_vendor_id')
    op.drop_column('candidates', 'bgv_status')
    # ### end Alembic commands ###
