"""add resume_url to imported_candidates

Revision ID: 29abeb7c48d6
Revises: 0f4632632f8a
Create Date: 2025-12-15 15:37:15.031215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29abeb7c48d6'
down_revision: Union[str, Sequence[str], None] = '0f4632632f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imported_candidates', sa.Column('resume_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imported_candidates', 'resume_url')
    # ### end Alembic commands ###
