"""add bgv fields

Revision ID: 2d6251d5dd84
Revises: 21eced7f43e0
Create Date: 2025-12-29 16:38:34.271242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6251d5dd84'
down_revision: Union[str, Sequence[str], None] = '21eced7f43e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('bgv_initiated', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('bgv_assigned_at', sa.DateTime(), nullable=True))
    op.add_column('candidates', sa.Column('bgv_report_url', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('bgv_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'bgv_completed_at')
    op.drop_column('candidates', 'bgv_report_url')
    op.drop_column('candidates', 'bgv_assigned_at')
    op.drop_column('candidates', 'bgv_initiated')
    # ### end Alembic commands ###
