"""Add vendor module tables

Revision ID: 3af49cce863f
Revises: 7c291acb76fc
Create Date: 2025-12-28 13:36:13.359457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af49cce863f'
down_revision: Union[str, Sequence[str], None] = '7c291acb76fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('vendor_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'vendors', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'vendor_id')
    # ### end Alembic commands ###
