"""add candidate forwarding fields

Revision ID: 4106fc762996
Revises: bf4867a0965c
Create Date: 2025-12-12 15:59:36.357962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4106fc762996'
down_revision: Union[str, Sequence[str], None] = 'bf4867a0965c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('applied_job_id', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('forwarded_to', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('forward_note', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('forwarded_at', sa.DateTime(), nullable=True))
    op.drop_column('candidates', 'job_applied')
    op.add_column('jobs', sa.Column('job_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_column('jobs', 'job_id')
    op.add_column('candidates', sa.Column('job_applied', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('candidates', 'forwarded_at')
    op.drop_column('candidates', 'forward_note')
    op.drop_column('candidates', 'forwarded_to')
    op.drop_column('candidates', 'applied_job_id')
    # ### end Alembic commands ###
