"""fix imported_candidate bulk upload schema

Revision ID: 5cc03663ede6
Revises: 157a50b4842c
Create Date: 2025-12-15 12:00:05.049534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc03663ede6'
down_revision: Union[str, Sequence[str], None] = '157a50b4842c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # -------------------------------
    # CANDIDATES TABLE (SAFE CASTING)
    # -------------------------------
    op.alter_column(
        "candidates",
        "current_address",
        type_=sa.Text(),
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "permanent_address",
        type_=sa.Text(),
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "application_date",
        type_=sa.DateTime(),
        postgresql_using="NULLIF(application_date, '')::timestamp",
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "resume_url",
        type_=sa.Text(),
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "cover_letter_url",
        type_=sa.Text(),
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "certificates_url",
        type_=sa.Text(),
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "photo_url",
        type_=sa.Text(),
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "sign_url",
        type_=sa.Text(),
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "experience_years",
        type_=sa.Float(),
        postgresql_using="NULLIF(experience_years, '')::float",
        existing_nullable=True,
    )

    # ⚠️ Convert STRING → JSON safely
    op.alter_column(
        "candidates",
        "education",
        type_=sa.JSON(),
        postgresql_using="to_jsonb(education)",
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "previous_employers",
        type_=sa.JSON(),
        postgresql_using="to_jsonb(previous_employers)",
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "languages_known",
        type_=sa.JSON(),
        postgresql_using="to_jsonb(languages_known)",
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "social_profiles",
        type_=sa.JSON(),
        postgresql_using="to_jsonb(social_profiles)",
        existing_nullable=True,
    )

    op.alter_column(
        "candidates",
        "last_login",
        type_=sa.DateTime(),
        postgresql_using="NULLIF(last_login, '')::timestamp",
        existing_nullable=True,
    )



    # ----------------------------------
    # IMPORTED CANDIDATES (RAW STORAGE)
    # ----------------------------------
    op.alter_column("imported_candidates", "current_address", type_=sa.Text())
    op.alter_column("imported_candidates", "permanent_address", type_=sa.Text())
    op.alter_column("imported_candidates", "skills", type_=sa.Text())
    op.alter_column("imported_candidates", "education", type_=sa.Text())
    op.alter_column("imported_candidates", "previous_employers", type_=sa.Text())
    op.alter_column("imported_candidates", "languages_known", type_=sa.Text())
    op.alter_column("imported_candidates", "social_profiles", type_=sa.Text())
    op.alter_column("imported_candidates", "tags", type_=sa.Text())

    # ----------------------------------
    # JOB APPLICATIONS
    # ----------------------------------
    op.alter_column("job_applications", "resume_url", type_=sa.Text())



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_applications', 'resume_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('imported_candidates', 'tags',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('imported_candidates', 'social_profiles',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('imported_candidates', 'languages_known',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('imported_candidates', 'previous_employers',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('imported_candidates', 'education',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('imported_candidates', 'skills',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('imported_candidates', 'permanent_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('imported_candidates', 'current_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'social_profiles',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'languages_known',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'last_login',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'previous_employers',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'education',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'experience_years',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'sign_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'photo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'certificates_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'cover_letter_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'resume_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'application_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'permanent_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'current_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
