"""fix job-candidate relationship

Revision ID: 6027071d95f5
Revises: b07026265e36
Create Date: 2025-12-05 15:12:07.342476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6027071d95f5'
down_revision: Union[str, Sequence[str], None] = 'b07026265e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('fullName', sa.String(), nullable=True))
    op.drop_column('candidates', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('candidates', 'fullName')
    # ### end Alembic commands ###
