"""update user add full_name

Revision ID: 777500c36261
Revises: 64f456d9e471
Create Date: 2025-12-08 11:36:56.098201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '777500c36261'
down_revision: Union[str, Sequence[str], None] = '64f456d9e471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recipient_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('communication_logs_pkey'))
    )
    # ### end Alembic commands ###
