"""add job_id to requirement

Revision ID: 7c291acb76fc
Revises: e95770b840fd
Create Date: 2025-12-26 16:33:44.871752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c291acb76fc'
down_revision: Union[str, Sequence[str], None] = 'e95770b840fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('job_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'requirements', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.drop_column('requirements', 'job_id')
    # ### end Alembic commands ###
