"""add candidate_id and public_id to imported_candidates

Revision ID: 83497ae7f8a2
Revises: 29abeb7c48d6
Create Date: 2025-12-15 17:48:56.894762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83497ae7f8a2'
down_revision: Union[str, Sequence[str], None] = '29abeb7c48d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imported_candidates', sa.Column('candidate_id', sa.String(), nullable=True))
    op.add_column('imported_candidates', sa.Column('public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imported_candidates', 'public_id')
    op.drop_column('imported_candidates', 'candidate_id')
    # ### end Alembic commands ###
