"""add screening_score to job_applications

Revision ID: 847158f31a81
Revises: 8fb6043a7f91
Create Date: 2025-12-19 14:07:31.292925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847158f31a81'
down_revision: Union[str, Sequence[str], None] = '8fb6043a7f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('screening_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'screening_score')
    # ### end Alembic commands ###
