"""add manager_id to employees

Revision ID: 85e0cfc6ede4
Revises: ca26890a188e
Create Date: 2025-12-10 11:57:02.776385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85e0cfc6ede4'
down_revision: Union[str, Sequence[str], None] = 'ca26890a188e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.create_foreign_key(None, 'alumni', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(op.f('document_audits_document_id_fkey'), 'document_audits', type_='foreignkey')
    op.create_foreign_key(None, 'employee_salaries', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'exit_interviews', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'leave_balances', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'leave_requests', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'onboarding_tasks', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'payslips', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'performance_reviews', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'salary_deductions', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salary_deductions', type_='foreignkey')
    op.drop_constraint(None, 'performance_reviews', type_='foreignkey')
    op.drop_constraint(None, 'payslips', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_tasks', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.drop_constraint(None, 'exit_interviews', type_='foreignkey')
    op.drop_constraint(None, 'employee_salaries', type_='foreignkey')
    op.create_foreign_key(op.f('document_audits_document_id_fkey'), 'document_audits', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'alumni', type_='foreignkey')
    op.create_table('documents',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('documents_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    # ### end Alembic commands ###
