"""Add client fields and client workflow columns

Revision ID: 8d20f8ebc0db
Revises: 9e0eb27dc4c4
Create Date: 2025-12-20 21:25:55.549089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d20f8ebc0db'
down_revision: Union[str, Sequence[str], None] = '9e0eb27dc4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultant_deployments', sa.Column('client_id', sa.String(), nullable=True))
    op.add_column('job_applications', sa.Column('client_feedback', sa.Text(), nullable=True))
    op.add_column('job_applications', sa.Column('client_decision', sa.String(length=50), nullable=True))
    op.add_column('job_applications', sa.Column('sent_to_client_at', sa.DateTime(), nullable=True))
    op.add_column('job_applications', sa.Column('decision_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('client_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'client_id')
    op.drop_column('job_applications', 'decision_at')
    op.drop_column('job_applications', 'sent_to_client_at')
    op.drop_column('job_applications', 'client_decision')
    op.drop_column('job_applications', 'client_feedback')
    op.drop_column('consultant_deployments', 'client_id')
    # ### end Alembic commands ###
