"""add consultant and employee changes

Revision ID: 8e1e0cc9ce70
Revises: a2804d8771a8
Create Date: 2026-01-05 16:37:10.641371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e1e0cc9ce70'
down_revision: Union[str, Sequence[str], None] = 'a2804d8771a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ❌ REMOVED employee_logs DROP (VERY IMPORTANT)

    op.alter_column(
        'candidates',
        'profile_completion',
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text('0')
    )

    # ---------- CONSULTANTS ----------
    op.add_column('consultants', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('consultants', sa.Column('consultant_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'consultants', ['consultant_code'])
    op.create_foreign_key(None, 'consultants', 'users', ['user_id'], ['id'])

    op.drop_column('consultants', 'full_name')
    op.drop_column('consultants', 'email')
    op.drop_column('consultants', 'phone')
    op.drop_column('consultants', 'sourcing_fee_type')
    op.drop_column('consultants', 'sourcing_fee_amount')

    # ---------- EMPLOYEES ----------
    op.alter_column('employees', 'candidate_id', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('employees', 'user_id', existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(None, 'employees', ['candidate_id'])

    op.drop_column('employees', 'email')
    op.drop_column('employees', 'full_name')
    op.drop_column('employees', 'phone')

    # ---------- REQUIREMENTS ----------
    op.drop_constraint(op.f('uq_requirements_requirement_code'), 'requirements', type_='unique')
    op.create_index(
        op.f('ix_requirements_requirement_code'),
        'requirements',
        ['requirement_code'],
        unique=True
    )

    # ---------- USERS ----------
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('linked_candidate_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'candidates', ['linked_candidate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'linked_candidate_id')
    op.drop_column('users', 'must_change_password')
    op.drop_index(op.f('ix_requirements_requirement_code'), table_name='requirements')
    op.create_unique_constraint(op.f('uq_requirements_requirement_code'), 'requirements', ['requirement_code'])
    op.add_column('employees', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='unique')
    op.alter_column('employees', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'candidate_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('consultants', sa.Column('sourcing_fee_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('consultants', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('consultants', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('consultants', sa.Column('sourcing_fee_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('consultants', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'consultants', type_='foreignkey')
    op.drop_constraint(None, 'consultants', type_='unique')
    op.drop_column('consultants', 'consultant_code')
    op.drop_column('consultants', 'user_id')
    op.alter_column('candidates', 'profile_completion',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_table('employee_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('old_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('employee_logs_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_logs_pkey'))
    )
    op.create_index(op.f('ix_employee_logs_id'), 'employee_logs', ['id'], unique=False)
    # ### end Alembic commands ###
