"""add candidate social + ctc fields

Revision ID: 8fb6043a7f91
Revises: 60aa6c27d8e2
Create Date: 2025-12-19 13:41:15.945508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb6043a7f91'
down_revision: Union[str, Sequence[str], None] = '60aa6c27d8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('github_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('portfolio_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('expected_ctc', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('date_of_birth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'date_of_birth')
    op.drop_column('candidates', 'experience')
    op.drop_column('candidates', 'expected_ctc')
    op.drop_column('candidates', 'portfolio_url')
    op.drop_column('candidates', 'github_url')
    op.drop_column('candidates', 'linkedin_url')
    # ### end Alembic commands ###
