"""add final bgv fields

Revision ID: 953c56ef011b
Revises: 2d6251d5dd84
Create Date: 2025-12-29 17:32:09.722396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953c56ef011b'
down_revision: Union[str, Sequence[str], None] = '2d6251d5dd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('bgv_final_status', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('bgv_final_remarks', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('bgv_final_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'bgv_final_verified_at')
    op.drop_column('candidates', 'bgv_final_remarks')
    op.drop_column('candidates', 'bgv_final_status')
    # ### end Alembic commands ###
