"""Vendor Candidate Support

Revision ID: a211d69a5b12
Revises: 3af49cce863f
Create Date: 2025-12-28 13:40:04.480131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a211d69a5b12'
down_revision: Union[str, Sequence[str], None] = '3af49cce863f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('is_vendor_candidate', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('billing_rate', sa.Float(), nullable=True))
    op.add_column('candidates', sa.Column('payout_rate', sa.Float(), nullable=True))
    op.drop_constraint(op.f('candidates_email_key'), 'candidates', type_='unique')
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.drop_constraint(op.f('candidates_vendor_id_fkey'), 'candidates', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('candidates_vendor_id_fkey'), 'candidates', 'vendors', ['vendor_id'], ['id'])
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.create_unique_constraint(op.f('candidates_email_key'), 'candidates', ['email'])
    op.drop_column('candidates', 'payout_rate')
    op.drop_column('candidates', 'billing_rate')
    op.drop_column('candidates', 'is_vendor_candidate')
    # ### end Alembic commands ###
