"""fix job-candidate relationship

Revision ID: a4c9960013fd
Revises: 6027071d95f5
Create Date: 2025-12-05 15:31:24.199763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c9960013fd'
down_revision: Union[str, Sequence[str], None] = '6027071d95f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('full_name', sa.String(), nullable=True))
    op.drop_column('candidates', 'fullName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('fullName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('candidates', 'full_name')
    # ### end Alembic commands ###
