"""add meeting link to interviews

Revision ID: a8942d5260af
Revises: a211d69a5b12
Create Date: 2025-12-29 01:06:25.861361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8942d5260af'
down_revision: Union[str, Sequence[str], None] = 'a211d69a5b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('meeting_link', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'notes')
    op.drop_column('interviews', 'meeting_link')
    # ### end Alembic commands ###
