"""add candidate public_id

Revision ID: ab8dfa29659b
Revises: df3d74f348df
Create Date: 2025-12-09 12:33:03.558630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8dfa29659b'
down_revision: Union[str, Sequence[str], None] = 'df3d74f348df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    # 1️⃣ Pehle sab NULL full_name ko temporary value assign karo
    op.execute("UPDATE candidates SET full_name = 'Unknown Candidate' WHERE full_name IS NULL;")

    # 2️⃣ Ab public_id add karo
    op.add_column('candidates', sa.Column('public_id', sa.String(), nullable=True))

    # 3️⃣ full_name ko NOT NULL set kar do
    op.alter_column(
        'candidates',
        'full_name',
        existing_type=sa.VARCHAR(),
        nullable=False
    )

    # 4️⃣ public_id ko unique index do (later generate ID fill karenge)
    op.create_index(op.f('ix_candidates_public_id'), 'candidates', ['public_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_public_id'), table_name='candidates')
    op.alter_column('candidates', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('candidates', 'public_id')
    # ### end Alembic commands ###
