"""fix job-candidate relationship

Revision ID: b07026265e36
Revises: 1577d91c5831
Create Date: 2025-12-05 14:23:48.553446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07026265e36'
down_revision: Union[str, Sequence[str], None] = '1577d91c5831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('current_location', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('current_address', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('permanent_address', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('job_applied', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('application_date', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('referral', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('resume_version', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('cover_letter_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('certificates_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('sign_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('experience_years', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('education', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('current_employer', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('previous_employers', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('notice_period', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('last_login', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('internal_notes', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('expected_salary', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('preferred_location', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('languages_known', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('social_profiles', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('interview_stage', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('interview_feedback', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    op.alter_column('candidates', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('candidates_applied_job_id_fkey'), 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'fit_score')
    op.drop_column('candidates', 'fit_explanation')
    op.drop_column('candidates', 'applied_job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('applied_job_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('fit_explanation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('fit_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('candidates_applied_job_id_fkey'), 'candidates', 'jobs', ['applied_job_id'], ['id'])
    op.alter_column('candidates', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('candidates', 'profile_completed')
    op.drop_column('candidates', 'interview_feedback')
    op.drop_column('candidates', 'interview_stage')
    op.drop_column('candidates', 'social_profiles')
    op.drop_column('candidates', 'languages_known')
    op.drop_column('candidates', 'preferred_location')
    op.drop_column('candidates', 'expected_salary')
    op.drop_column('candidates', 'internal_notes')
    op.drop_column('candidates', 'last_login')
    op.drop_column('candidates', 'notice_period')
    op.drop_column('candidates', 'previous_employers')
    op.drop_column('candidates', 'current_employer')
    op.drop_column('candidates', 'education')
    op.drop_column('candidates', 'experience_years')
    op.drop_column('candidates', 'skills')
    op.drop_column('candidates', 'sign_url')
    op.drop_column('candidates', 'photo_url')
    op.drop_column('candidates', 'certificates_url')
    op.drop_column('candidates', 'cover_letter_url')
    op.drop_column('candidates', 'resume_version')
    op.drop_column('candidates', 'referral')
    op.drop_column('candidates', 'application_date')
    op.drop_column('candidates', 'job_applied')
    op.drop_column('candidates', 'permanent_address')
    op.drop_column('candidates', 'current_address')
    op.drop_column('candidates', 'current_location')
    # ### end Alembic commands ###
