"""add employee log table

Revision ID: bd7965cb4e89
Revises: 5d564742ded0
Create Date: 2025-12-11 13:50:14.737222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7965cb4e89'
down_revision: Union[str, Sequence[str], None] = '5d564742ded0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_employee_logs_id'), 'employee_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_logs_id'), table_name='employee_logs')
    op.alter_column('employee_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
