"""fix job_recruiters table

Revision ID: cdb5b98df6f9
Revises: 3fc14ec610fa
Create Date: 2025-12-23 13:50:38.861855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb5b98df6f9'
down_revision: Union[str, Sequence[str], None] = '3fc14ec610fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_recruiters',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('recruiter_id', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'recruiter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_recruiters')
    # ### end Alembic commands ###
