"""add missing fields to job_applications

Revision ID: db9995969979
Revises: 5cc03663ede6
Create Date: 2025-12-15 12:53:10.489780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db9995969979'
down_revision: Union[str, Sequence[str], None] = '5cc03663ede6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('candidates', 'expected_salary',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.add_column('job_applications', sa.Column('resume_version', sa.String(), nullable=True))
    # op.add_column('job_applications', sa.Column('cover_letter_url', sa.Text(), nullable=True))
    # op.add_column('job_applications', sa.Column('certificates_url', sa.Text(), nullable=True))
    # op.add_column('job_applications', sa.Column('photo_url', sa.Text(), nullable=True))
    # op.add_column('job_applications', sa.Column('sign_url', sa.Text(), nullable=True))
    # op.add_column('job_applications', sa.Column('skills', sa.JSON(), nullable=True))
    # op.add_column('job_applications', sa.Column('experience_years', sa.Float(), nullable=True))
    # op.add_column('job_applications', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    # op.drop_index(op.f('ix_job_applications_candidate_id'), table_name='job_applications')
    # op.drop_index(op.f('ix_job_applications_job_id'), table_name='job_applications')
    # op.drop_constraint(op.f('job_applications_reviewed_by_fkey'), 'job_applications', type_='foreignkey')
    # op.drop_column('job_applications', 'screening_notes')
    # op.drop_column('job_applications', 'portfolio_url')
    # op.drop_column('job_applications', 'screening_score')
    # op.drop_column('job_applications', 'reviewed_by')
    # op.drop_column('job_applications', 'reviewed_at')
    # op.drop_column('job_applications', 'linkedin_url')
    # op.drop_column('job_applications', 'cover_letter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('cover_letter', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('job_applications', sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_applications', sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('job_applications', sa.Column('reviewed_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_applications', sa.Column('screening_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('job_applications', sa.Column('portfolio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_applications', sa.Column('screening_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('job_applications_reviewed_by_fkey'), 'job_applications', 'users', ['reviewed_by'], ['id'])
    op.create_index(op.f('ix_job_applications_job_id'), 'job_applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_applications_candidate_id'), 'job_applications', ['candidate_id'], unique=False)
    op.drop_column('job_applications', 'profile_completed')
    op.drop_column('job_applications', 'experience_years')
    op.drop_column('job_applications', 'skills')
    op.drop_column('job_applications', 'sign_url')
    op.drop_column('job_applications', 'photo_url')
    op.drop_column('job_applications', 'certificates_url')
    op.drop_column('job_applications', 'cover_letter_url')
    op.drop_column('job_applications', 'resume_version')
    op.alter_column('candidates', 'expected_salary',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
