import { useCallback } from 'react';
import { apiService } from '../api/axios';

/**
 * Hook for logging recruiter activities on requirements
 * This helps track engagement and prevent requirements from becoming passive
 */
const useActivityLogger = () => {
  const logActivity = useCallback(async (requirementId, activityType, description = '', metadata = {}) => {
    try {
      if (!requirementId || !activityType) {
        console.warn('Activity logger: missing requirementId or activityType');
        return false;
      }\n\n      await apiService.post(`/api/requirements/${requirementId}/activity`, {\n        activity_type: activityType,\n        description: description,\n        metadata: metadata\n      });\n\n      return true;\n    } catch (error) {\n      console.error('Failed to log activity:', error);\n      return false;\n    }\n  }, []);\n\n  // Convenience methods for common activity types\n  const logView = useCallback((requirementId, description = 'Viewed requirement') => {\n    return logActivity(requirementId, 'view', description);\n  }, [logActivity]);\n\n  const logEdit = useCallback((requirementId, description = 'Edited requirement', changes = {}) => {\n    return logActivity(requirementId, 'edit', description, { changes });\n  }, [logActivity]);\n\n  const logComment = useCallback((requirementId, comment) => {\n    return logActivity(requirementId, 'comment', `Added comment: ${comment}`);\n  }, [logActivity]);\n\n  const logCandidateSubmission = useCallback((requirementId, candidateId, candidateName = '') => {\n    return logActivity(\n      requirementId, \n      'submit_candidate', \n      `Submitted candidate: ${candidateName}`,\n      { candidate_id: candidateId, candidate_name: candidateName }\n    );\n  }, [logActivity]);\n\n  const logCandidateSearch = useCallback((requirementId, searchQuery, resultsCount = 0) => {\n    return logActivity(\n      requirementId, \n      'candidate_search', \n      `Searched for candidates: \"${searchQuery}\"`,\n      { search_query: searchQuery, results_count: resultsCount }\n    );\n  }, [logActivity]);\n\n  const logStatusChange = useCallback((requirementId, oldStatus, newStatus) => {\n    return logActivity(\n      requirementId, \n      'status_change', \n      `Changed status from ${oldStatus} to ${newStatus}`,\n      { old_status: oldStatus, new_status: newStatus }\n    );\n  }, [logActivity]);\n\n  const logCommunication = useCallback((requirementId, communicationType, description) => {\n    return logActivity(\n      requirementId, \n      'communication', \n      `${communicationType}: ${description}`,\n      { communication_type: communicationType }\n    );\n  }, [logActivity]);\n\n  const logReview = useCallback((requirementId, description = 'Reviewed requirement details') => {\n    return logActivity(requirementId, 'review', description);\n  }, [logActivity]);\n\n  return {\n    logActivity,\n    logView,\n    logEdit,\n    logComment,\n    logCandidateSubmission,\n    logCandidateSearch,\n    logStatusChange,\n    logCommunication,\n    logReview\n  };\n};\n\nexport default useActivityLogger;